package TestCases;


// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import TestCases.PO.*;

public class TestCases {


    private WebDriver driver;

    private Map<String, Object> vars;

    private JavascriptExecutor js;
    private AddNewQuestionPO _AddNewQuestionPO;

    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();

        _AddNewQuestionPO = new AddNewQuestionPO(driver, js, vars);
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void enrolUser() {
        driver.get("http://localhost:3000/claroline11110/index.php");
        LoginPagePO _LoginPagePO = new LoginPagePO(driver, js, vars);
        _LoginPagePO.loginTo("user001", "password001");
        MyDesktopPO _MyDesktopPO = new MyDesktopPO(driver, js, vars);
        _MyDesktopPO.clickToEnrolOnANewCourse();
        UsersCoursesPO _UsersCoursesPO = new UsersCoursesPO(driver, js, vars);
        _UsersCoursesPO.searchforCourse("Course001");
        assertThat(_UsersCoursesPO.set_CSSSELECTOR_claroDialogMsg_1(), is("You\'ve been enrolled on the course"));
        _MyDesktopPO.clickToLogout();
    }

    @Test
    public void searchCourse() {
        driver.get("http://localhost:3000/claroline11110/index.php");
        LoginPagePO _LoginPagePO = new LoginPagePO(driver, js, vars);
        _LoginPagePO.loginTo("admin", "admin");
        MyDesktopPO _MyDesktopPO = new MyDesktopPO(driver, js, vars);
        _MyDesktopPO.clickToPlatformAdministrationLink();
        PlatformAdministrationPO _PlatformAdministrationPO = new PlatformAdministrationPO(driver, js, vars);
        _PlatformAdministrationPO.SearchForaCourse("Course001");
        assertThat(_PlatformAdministrationPO.set_CSSSELECTOR_ab_1(), is("Course001"));
        assertThat(_PlatformAdministrationPO.set_ID_L0(), is("001"));
        _MyDesktopPO.clickToLogout();
    }

    @Test
    public void addCourse() {
        driver.get("http://localhost:3000/claroline11110/index.php");
        LoginPagePO _LoginPagePO = new LoginPagePO(driver, js, vars);
        _LoginPagePO.loginTo("admin", "admin");
        MyDesktopPO _MyDesktopPO = new MyDesktopPO(driver, js, vars);
        _MyDesktopPO.clickToPlatformAdministrationLink();
        PlatformAdministrationPO _PlatformAdministrationPO = new PlatformAdministrationPO(driver, js, vars);
        _PlatformAdministrationPO.clickToCreateCourseLink();
        CreateNewCoursePO _CreateNewCoursePO = new CreateNewCoursePO(driver, js, vars);
        _CreateNewCoursePO.enterCourseDetails("Course001", "001", "Sciences", "Economics");
        assertThat(_CreateNewCoursePO.set_CSSSELECTOR_claroDialogMsg(), is("You have just created the course website : 001"));
        _CreateNewCoursePO.clickToContinue();
        _MyDesktopPO.clickToLogout();
    }

    @Test
    public void addEventToCourse() {
        driver.get("http://localhost:3000/claroline11110/index.php");
        LoginPagePO _LoginPagePO = new LoginPagePO(driver, js, vars);
        _LoginPagePO.loginTo("admin", "admin");
        MyDesktopPO _MyDesktopPO = new MyDesktopPO(driver, js, vars);
        _MyDesktopPO.clickToCourse001();
        CoursePagePO _CoursePagePO = new CoursePagePO(driver, js, vars);
        _CoursePagePO.clickToAgentaIcon("Exam 001", "31", "May", "2023", "Genoa");
        assertThat(_CoursePagePO.set_CSSSELECTOR_claroDialogMsg_1(), is("Event added to the agenda."));
        _MyDesktopPO.clickToLogout();
    }

    @Test
    public void addExerciseToCourse() {
        driver.get("http://localhost:3000/claroline11110/index.php");
        driver.findElement(By.id("login")).click();
        LoginPagePO _LoginPagePO = new LoginPagePO(driver, js, vars);
        _LoginPagePO.loginTo("admin", "admin");
        MyDesktopPO _MyDesktopPO = new MyDesktopPO(driver, js, vars);
        _MyDesktopPO.clickToCourse001();
        CoursePagePO _CoursePagePO = new CoursePagePO(driver, js, vars);
        _CoursePagePO.clickToExerciseIcon("Exercise 001");
        assertThat(_CoursePagePO.set_CSSSELECTOR_claroDialogMsg_1(), is("Exercise added"));
        _MyDesktopPO.clickToLogout();
    }

    @Test
    public void addUserToSystem() {
        driver.get("http://localhost:3000/claroline11110/index.php");
        LoginPagePO _LoginPagePO = new LoginPagePO(driver, js, vars);
        _LoginPagePO.loginTo("admin", "admin");
        MyDesktopPO _MyDesktopPO = new MyDesktopPO(driver, js, vars);
        _MyDesktopPO.clickToPlatformAdministrationLink();
        PlatformAdministrationPO _PlatformAdministrationPO = new PlatformAdministrationPO(driver, js, vars);
        _PlatformAdministrationPO.clickToCreateUser();
        CreateNewUserPO _CreateNewUserPO = new CreateNewUserPO(driver, js, vars);
        _CreateNewUserPO.enterNewUserDetails("Name001", "firstname001", "user001", "password001", "password001");
        assertThat(_CreateNewUserPO.set_CSSSELECTOR_msgSuccess_1(), is("The new user has been sucessfully created"));
        _MyDesktopPO.clickToLogout();
    }

    @Test
    public void loginAsUser() {
        driver.get("http://localhost:3000/claroline11110/index.php");
        AutoPo _AutoPo = new AutoPo(driver, js, vars);
        _AutoPo.set_ID_login("user001", "password001");
        LoginPagePO _LoginPagePO = new LoginPagePO(driver, js, vars);
        _LoginPagePO.clickToEnterBtn_1();
        assertThat(_LoginPagePO.set_CSSSELECTOR_blockHeaderuserName_1(), is("firstname001 Name001"));
        MyDesktopPO _MyDesktopPO = new MyDesktopPO(driver, js, vars);
        _MyDesktopPO.clickToLogout();
    }

    @Test
    public void searchUser() {
        driver.get("http://localhost:3000/claroline11110/index.php");
        LoginPagePO _LoginPagePO = new LoginPagePO(driver, js, vars);
        _LoginPagePO.loginTo("admin", "admin");
        MyDesktopPO _MyDesktopPO = new MyDesktopPO(driver, js, vars);
        _MyDesktopPO.clickToPlatformAdministrationLink();
        PlatformAdministrationPO _PlatformAdministrationPO = new PlatformAdministrationPO(driver, js, vars);
        _PlatformAdministrationPO.searchForaUser("user001");
        assertThat(_PlatformAdministrationPO.set_CSSSELECTOR_tdnth_child3_1(), is("firstname001"));
        assertThat(_PlatformAdministrationPO.set_CSSSELECTOR_tdnth_child6(), is("User"));
        _MyDesktopPO.clickToLogout();
    }

    @Test
    public void makeCourseExerciseVisible() {
        driver.get("http://localhost:3000/claroline11110/index.php");
        LoginPagePO _LoginPagePO = new LoginPagePO(driver, js, vars);
        _LoginPagePO.loginTo("admin", "admin");
        MyDesktopPO _MyDesktopPO = new MyDesktopPO(driver, js, vars);
        _MyDesktopPO.clickToCourse001();
        CoursePagePO _CoursePagePO = new CoursePagePO(driver, js, vars);
        _CoursePagePO.clickToExerciseIcon_1();
        assertThat(_CoursePagePO.getVisibilityIconAltTextForRow(2), is("Make visible"));
        _CoursePagePO.makeExerciseVisible();
        assertThat(_CoursePagePO.getVisibilityIconAltTextForRow(2), is("Make invisible"));
        _MyDesktopPO.clickToLogout();
    }


    @Test
    public void addQuestionsToExercise() throws InterruptedException{
        driver.get("http://localhost:3000/claroline11110/index.php");
        LoginPagePO _LoginPagePO = new LoginPagePO(driver, js, vars);
        _LoginPagePO.loginTo("admin", "admin");
        MyDesktopPO _MyDesktopPO = new MyDesktopPO(driver, js, vars);
        _MyDesktopPO.clickToCourse001();
        CoursePagePO _CoursePagePO = new CoursePagePO(driver, js, vars);
        _CoursePagePO.clickToExerciseIcon_1();
        _CoursePagePO.clickToModifyIcon();

        //Question 1
        _AddNewQuestionPO.clickNewQuestionLink();
        _AddNewQuestionPO.enterQuestionTitle("Question 1");
        _AddNewQuestionPO.selectQuestionType("MCUA");
      Thread.sleep(3000);
        _AddNewQuestionPO.clickOkButton();
      
        _AddNewQuestionPO.selectFirstAnswer();
        _AddNewQuestionPO.clearAndEnterWeightingForAnswer(1, "3");
        _AddNewQuestionPO.clearAndEnterWeightingForAnswer(2, "-3");
        _AddNewQuestionPO.clickOKBtn();

        //Question 2
        _AddNewQuestionPO.clickNewQuestionLink();
        _AddNewQuestionPO.enterQuestionTitle("Question 2");
        _AddNewQuestionPO.selectQuestionType("TF");
        Thread.sleep(3000);
        _AddNewQuestionPO.clickOkButton();
        _AddNewQuestionPO.selectFirstAnswer();
        _AddNewQuestionPO.clearAndEnterWeightingForTF("true", "3");
        _AddNewQuestionPO.clearAndEnterWeightingForTF("false", "-3");
        _AddNewQuestionPO.clickOKBtn();

        //Question 3
        _AddNewQuestionPO.clickNewQuestionLink();
        _AddNewQuestionPO.enterQuestionTitle("Question 3");
        _AddNewQuestionPO.selectQuestionType("MCMA");
        Thread.sleep(2000);
        _AddNewQuestionPO.clickOkButton();
        _AddNewQuestionPO.clickAddAnswerButton();
        _AddNewQuestionPO.selectFirstCheckbox();
        _AddNewQuestionPO.clearAndEnterWeightingForAnswer(1, "3");
        _AddNewQuestionPO.clearAndEnterWeightingForAnswer(2, "0");
        _AddNewQuestionPO.clearAndEnterWeightingForAnswer(3, "-3");
        _AddNewQuestionPO.clickOKBtn();

        _AddNewQuestionPO.clickExerciseLink();

        assertThat(_CoursePagePO.getQuestionTitleForRow(1), is("Question 1"));
        assertThat(_CoursePagePO.getAnswerTypeForRow(1), is("Multiple choice (Unique answer)"));
        assertThat(_CoursePagePO.getQuestionTitleForRow(2), is("Question 2"));
        assertThat(_CoursePagePO.getAnswerTypeForRow(2), is("True/False"));
        assertThat(_CoursePagePO.getQuestionTitleForRow(3), is("Question 3"));
        assertThat(_CoursePagePO.getAnswerTypeForRow(3), is("Multiple choice (Multiple answers)"));
        
        // Logout
        _MyDesktopPO.clickToLogout();
    }
}
