package TestCases;


import org.junit.After;
import org.junit.Before;
// Generated by Selenium IDE
import org.junit.Test;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import TestCases.PO.*;

public class addIssueTest {

    private WebDriver driver;

    private Map<String, Object> vars;

    private JavascriptExecutor js;
    private LoginPagePO _LoginPagePO;
    private ViewPagePO _ViewPagePO;
    private ReportIssuePO _ReportIssuePO;
    private AssignIssuePO _AssignIssuePO;

    
    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        _LoginPagePO = new LoginPagePO(driver, js, vars);
        _ViewPagePO = new ViewPagePO(driver, js, vars);
        _ReportIssuePO = new ReportIssuePO(driver, js, vars);
        _AssignIssuePO = new AssignIssuePO(driver, js, vars);
        _LoginPagePO.enterUsername("administrator");
        _LoginPagePO.enterPassword("root");
        _LoginPagePO.clickToLoginBtn();
    }

    @After
    public void tearDown() {
        driver.close();
    }

    @Test
    public void login2() throws InterruptedException {    
        Thread.sleep(3000);
        assertThat(_LoginPagePO.set_CSSSELECTOR_login_info_left_1(), is("Logged in as: administrator (administrator)"));
        _ViewPagePO.clickToLogoutLink();
    }

    @Test
    public void addIssue() {
        _ViewPagePO.clickToReportIssueLink();
        _ReportIssuePO.enterReportDetails("[All Projects] Category001", "random", "crash", "immediate", "Summary001", "description001");
        _ViewPagePO.clickToViewIssuesLink_1();
        assertThat(_ViewPagePO.set_CSSSELECTOR_centernth_child6_1(), is("Category001"));
        assertThat(_ViewPagePO.set_CSSSELECTOR_centernth_child7bold(), is("crash"));
        assertThat(_ViewPagePO.set_CSSSELECTOR_leftnth_child10(), is("Summary001"));
        _ViewPagePO.clickToLogoutLink();
    }  

    @Test
    public void assignIssue() throws InterruptedException {

        _ViewPagePO.clickToViewIssuesLink();
        _AssignIssuePO.assignIssue("Assign");
        Thread.sleep(3000);
        assertThat(_AssignIssuePO.set_CSSSELECTOR_centernth_child8_1(), is("assigned (administrator)"));
        _ViewPagePO.clickToLogoutLink();
    }
}
